name: PyMeasure rf_lab CI
on:
  push:
    branches:
      - rf_lab

jobs:
  docs_lint:
    name: Docs and Linting
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache conda
        uses: actions/cache@v3
        env:
          CACHE_NUMBER: 0  # Increase to reset the cache
        with:
          path: ~/conda_pkgs_dir
          key: py3.8-ubuntu-latest-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('requirements/*.yml') }}
      - name: Install pymeasure requirements
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"
          environment-file: requirements/pymeasure.yml
          activate-environment: pymeasure
          auto-update-conda: true
          use-only-tar-bz2: true  # for caching to work properly
      - name: Conda info & list
        run: |
          conda info
          conda list
      - name: Set up flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Lint with flake8
        run: |
          # Be sure to check for Python syntax errors or undefined names
          flake8 . --count --extend-select=E9,F63,F7,F82 --show-source --statistics
      - uses: ammaraskar/sphinx-problem-matcher@master
      - name: Generate docs
        if: always()  # run even if the previous step failed
        working-directory: ./docs
        run: |
          echo "::add-matcher::.github/sphinx.json"
          make html SPHINXOPTS="-W --keep-going"
  build_wheels:
    name: Build wheels on ubuntu-latest
    # to supply options, put them in 'env', like:
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Michele Sardo
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out src from Git
        uses: actions/checkout@v2

      - name: Build wheels
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git branch
          python -m pip install --user --upgrade build setuptools_scm
          python -c "import setuptools_scm;print(setuptools_scm.get_version())"
          python -m build

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl

      - name: Copy files for macOS or Linux
        if: runner.os == 'macOS' || runner.os == 'Linux'
        run: |
          echo ${{ runner.os }}
          mkdir -p ./wheeldist
          cp -r ./dist/*.whl ./wheeldist
      - name: Copy files for Windows
        if: runner.os == 'Windows'
        run: |
          echo ${{ runner.os }}
          mkdir wheeldist -ErrorAction SilentlyContinue
          xcopy /Y .\dist\*.whl .\wheeldist\
      - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "msmttchr@gmail.com"
          git pull
          git add ./wheeldist/*.whl
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
